# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./tmp/db:/Users/ericschneider/Documents/dev/pg/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
